# Generated by Django 3.1.2 on 2020-10-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkToPayRequest',
            fields=[
                ('id', models.CharField(blank=True, max_length=80, primary_key=True, serialize=False)),
                ('dev_reference', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('partial_payment', models.BooleanField(default=True)),
            ],
        ),
    ]
