# Generated by Django 3.1.2 on 2020-10-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linktopay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktopayrequest',
            name='allowed_payment_methods',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linktopayrequest',
            name='currency',
            field=models.CharField(default='MXN', max_length=30),
        ),
        migrations.AddField(
            model_name='linktopayrequest',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='linktopayrequest',
            name='email',
            field=models.EmailField(blank=True, default='correo@ejemplo.com', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='linktopayrequest',
            name='expiration_days',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linktopayrequest',
            name='failure_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='linktopayrequest',
            name='installments_type',
            field=models.IntegerField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='linktopayrequest',
            name='last_name',
            field=models.CharField(default='Prueba', max_length=30),
        ),
        migrations.AddField(
            model_name='linktopayrequest',
            name='name',
            field=models.CharField(default='Señor', max_length=30),
        ),
        migrations.AddField(
            model_name='linktopayrequest',
            name='pending_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='linktopayrequest',
            name='review_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='linktopayrequest',
            name='success_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
