# Generated by Django 3.1.2 on 2020-10-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linktopay', '0002_auto_20201029_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktopayrequest',
            name='installments_type',
            field=models.IntegerField(default=0),
        ),
    ]
