# Generated by Django 3.1.2 on 2020-10-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linktopay', '0003_auto_20201029_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktopayrequest',
            name='description',
            field=models.CharField(blank=True, default='Product description', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='linktopayrequest',
            name='expiration_days',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='linktopayrequest',
            name='failure_url',
            field=models.CharField(default='http:127.0.0.1:5000/failure', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='linktopayrequest',
            name='pending_url',
            field=models.CharField(default='http:127.0.0.1:5000/pending', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='linktopayrequest',
            name='review_url',
            field=models.CharField(default='http:127.0.0.1:5000/review', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='linktopayrequest',
            name='success_url',
            field=models.CharField(default='http:127.0.0.1:5000/success', max_length=500, null=True),
        ),
    ]
