# Generated by Django 3.1.2 on 2020-10-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linktopay', '0005_auto_20201029_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linktopayrequest',
            name='allowed_payment_methods',
        ),
        migrations.RemoveField(
            model_name='linktopayrequest',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='linktopayrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='linktopayrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='linktopayrequest',
            name='expiration_days',
        ),
        migrations.RemoveField(
            model_name='linktopayrequest',
            name='failure_url',
        ),
        migrations.RemoveField(
            model_name='linktopayrequest',
            name='installments_type',
        ),
        migrations.RemoveField(
            model_name='linktopayrequest',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='linktopayrequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='linktopayrequest',
            name='partial_payment',
        ),
        migrations.RemoveField(
            model_name='linktopayrequest',
            name='pending_url',
        ),
        migrations.RemoveField(
            model_name='linktopayrequest',
            name='review_url',
        ),
        migrations.RemoveField(
            model_name='linktopayrequest',
            name='success_url',
        ),
    ]
